name: Deploy Web Resources to CRM DEV

on:
  push:
    branches: [DEV]
  pull_request:
    branches: [DEV]

jobs:
  deploy-to-dev:
    runs-on: windows-latest  

    env:
      CRM_URL: ${{ vars.D365DEV_ENV_URL }}
      CRM_USERNAME: ${{ vars.D365DEV_USERNAME }}
      CRM_PASSWORD: ${{ vars.D365DEV_PASSWORD }}

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧰 Install Dynamics 365 PowerShell Module
        shell: powershell  
        run: |
          Install-Module Microsoft.Xrm.Data.PowerShell -Force -Scope CurrentUser -AllowClobber

      - name: 🚀 Deploy Web Resources to CRM
        shell: powershell
        run: |
          ./scripts/deploy-webresources.ps1 `
            -CrmUrl $env:CRM_URL `
            -Username $env:CRM_USERNAME `
            -Password $env:CRM_PASSWORD
