name: Deploy Web Resource to DEV (D365 On-Prem)

on:
  push:
    branches: [DEV]
  pull_request:
    branches: [DEV]

jobs:
  deploy-to-dev:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install PowerShell Module for D365
      run: |
        Install-Module Microsoft.Xrm.Data.PowerShell -Force -Scope CurrentUser

    - name: Deploy Web Resource to DEV
      shell: pwsh
      run: |
        ./scripts/deploy-webresources.ps1 `
          -CrmUrl "${{ secrets.D365DEV_ENV_URL }}" `
          -Username "${{ secrets.D365DEV_USERNAME }}" `
          -Password "${{ secrets.D365DEV_PASSWORD }}"
